<?php

declare(strict_types=1);

namespace Paymentic\Sdk\Shared\Enum;

enum ApiErrorCode: string
{
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case POINT_NOT_ACTIVE = 'POINT_NOT_ACTIVE';
    case POINT_NOT_FOUND = 'POINT_NOT_FOUND';
    case PATH_NOT_FOUND = 'PATH_NOT_FOUND';
    case METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
    case TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND';
    case POINT_REFUNDS_DISABLED = 'POINT_REFUNDS_DISABLED';
    case TRANSACTION_ALREADY_CAPTURED = 'TRANSACTION_ALREADY_CAPTURED';
    case TRANSACTION_INVALID_STATUS = 'TRANSACTION_INVALID_STATUS';
    case REFUND_GENERAL_ERROR = 'REFUND_GENERAL_ERROR';
    case TRANSACTION_NOT_CAPTURED = 'TRANSACTION_NOT_CAPTURED';
    case REFUND_NOT_FOUND = 'REFUND_NOT_FOUND';
    case REFUND_AMOUNT_TOO_HIGH = 'REFUND_AMOUNT_TOO_HIGH';
    case SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
    case TRANSACTION_MISSING_DATA = 'TRANSACTION_MISSING_DATA';
    case TRANSACTION_BLIK_PROCESSING_ERROR = 'TRANSACTION_BLIK_PROCESSING_ERROR';
    case PROVIDER_NOT_SUPPORTED = 'PROVIDER_NOT_SUPPORTED';
    case BLIK_ALIAS_NOT_FOUND = 'BLIK_ALIAS_NOT_FOUND';
    case BLIK_ALIAS_NOT_UNIQUE = 'BLIK_ALIAS_NOT_UNIQUE';

    public static function tryFromString(?string $code): ?self
    {
        if (null === $code) {
            return null;
        }

        return self::tryFrom($code);
    }
}
